name: ci

on:
  schedule:
    - cron: 30 12 * * 1
  push:
    paths:
      - Dockerfile
      - start.sh
      - cli.sh
    branches: main

jobs:
  build:
    strategy:
      matrix:
        version: ["stable", "develop", "v2.5.4"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/explodingcamera/pleroma

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            PLEROMA_VERSION=${{ matrix.version }}
          context: .
          file: ./Dockerfile
          tags: ghcr.io/explodingcamera/pleroma:${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
