name: ci

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        version: ["stable", "develop", "v2.4.5"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: explodingcamera/pleroma

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            PLEROMA_VERSION=${{ matrix.version }}
          context: .
          file: ./Dockerfile
          tags: explodingcamera/pleroma:${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
